'use strict';
(()=>{
 const E=window.TimelineEngine,events=window.ARCHIVE_EVENTS||[],$=s=>document.querySelector(s),BASE=55;
 const months=['janeiro','fevereiro','março','abril','maio','junho','julho','agosto','setembro','outubro','novembro','dezembro'];
 const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const headline=e=>{const re=/lavagem de dinheiro|peculato|organização criminosa|corrupção|golpe de Estado|tentativa de golpe|assassinato|assassinar|fraude|crimes? contra a humanidade|genocídio|homofóbica|invasão/gi;let out='',last=0;for(const m of e.title.matchAll(re)){out+=esc(e.title.slice(last,m.index))+'<strong class="headline-key">'+esc(m[0])+'</strong>';last=m.index+m[0].length;}return out+esc(e.title.slice(last));};
 const url=x=>{try{const u=new URL(x,location.href);return ['https:','http:','file:'].includes(u.protocol)?esc(u.href):'#';}catch{return '#';}};
 const format=d=>{const[y,m,day]=d.split('-');return `${day?Number(day)+' de ':''}${months[Number(m)-1]} de ${y}`;};
 const short=d=>{const[y,m,day]=d.split('-');return `${day}.${m}.${y}`;};
 const image=(e,cls)=>{const v=e.image.local||e.image.url;const src=/^data:image\/(jpeg|png|webp);base64,[A-Za-z0-9+/=]+$/.test(v)?v:url(v);return `<img class="${cls}" src="${src}" alt="${esc(e.image.alt)}" loading="lazy" decoding="async">`;};
 const categories=window.ArchiveCategories.themes, classify=window.ArchiveCategories.classify;
 const themeFor=e=>categories.find(t=>t.id===classify(e)[0]);
 const visible=events;
 const world=$('#world'),detail=$('#detail'),picker=$('#year-picker');
 let layout,reveal,scrollQueued=false,lastFocus=null,activeEvent=null,introTimer;
 function geometry(){const mobile=innerWidth<900;return{mobile,width:mobile?innerWidth/2-34:Math.min(415,Math.min(innerWidth,1200)/2-80)};}
 function ticksHTML(){return layout.ticks.map(t=>{const d=new Date(E.START+t.day*E.DAY),y=d.getUTCFullYear(),m=d.getUTCMonth(),year=m===0;return `<div class="tick ${year?'year-tick':'month-tick'}" style="top:${t.y}px"><span class="tick-label">${year?y:months[m].slice(0,3)}</span></div>`;}).join('');}
 function videoId(video){try{const u=new URL(video.url);const id=u.searchParams.get('v')||(u.hostname==='youtu.be'?u.pathname.slice(1):'');return /^[a-zA-Z0-9_-]{11}$/.test(id)?id:'';}catch{return '';}}
 function videoHTML(e){const id=videoId(e.video);return `<div class="video-player">${id?`<iframe class="video-frame" loading="lazy" src="https://www.youtube-nocookie.com/embed/${id}?playsinline=1" title="${esc(e.video.title||e.title)}" allow="encrypted-media; picture-in-picture; fullscreen" allowfullscreen></iframe>`:''}<a class="watch-video" href="${url(e.video.url)}" target="_blank" rel="noopener noreferrer">▶ ${id?'Abrir vídeo no YouTube':'Assistir ao vídeo na fonte'} ↗</a></div>`;}
 function storyHTML(card){const e=card.event;
 const media=e.highlight?(e.video?videoHTML(e):e.image?`<div class="story-media">${image(e,'story-image')}${e.image.previewLabel?`<span class="video-tag">${esc(e.image.previewLabel)}</span>`:''}</div>`:''):'';
 return `<article class="story ${card.side?'left':''} ${e.highlight?'important':''}" style="--theme:${themeFor(e).color};top:${card.y}px" data-event="${e.id}"><button class="story-open" data-event="${e.id}" aria-label="Abrir: ${esc(e.title)}"><time class="story-date" datetime="${e.date}">${short(e.date)}</time><h2>${headline(e)}</h2></button>${media}</article>`;
 }
 function positionElements(){world.style.height=layout.height+'px';$('#ticks').innerHTML=ticksHTML();for(const card of layout.cards){const story=world.querySelector(`.story[data-event="${card.event.id}"]`),node=world.querySelector(`.node[data-event="${card.event.id}"]`);story.style.top=card.y+'px';story.classList.toggle('left',card.side===1);node.style.top=card.y+'px';}updatePosition();}
 function render(){const geo=geometry();layout=E.layout(visible,geo.width,geo.mobile);
  $('#nodes').innerHTML=layout.cards.map(c=>`<button style="--theme:${themeFor(c.event).color};top:${c.y}px" class="node ${c.event.highlight?'featured':''}" data-event="${c.event.id}" aria-label="${esc(format(c.event.date)+' — '+c.event.title)}"></button>`).join('');
  $('#stories').innerHTML=layout.cards.map(storyHTML).join('');
  $('#year-options').querySelectorAll('button').forEach(b=>{b.disabled=!visible.some(e=>e.date.slice(0,4)===b.dataset.year);});
  if(reveal)reveal.disconnect();
  if('IntersectionObserver' in window){reveal=new IntersectionObserver(entries=>entries.forEach(e=>e.target.classList.toggle('visible',e.isIntersecting)),{rootMargin:'15% 0px 15% 0px',threshold:0});world.querySelectorAll('.story').forEach(el=>reveal.observe(el));}else world.querySelectorAll('.story').forEach(el=>el.classList.add('visible'));
  world.querySelectorAll('.story img').forEach(img=>img.addEventListener('error',()=>{img.classList.add('unavailable');img.alt='Imagem indisponível — consulte a fonte no registro';},{once:true}));
  positionElements();fitStories();
 }
 function fitStories(){
  const canvas=document.createElement('canvas'),ctx=canvas.getContext('2d');
  if(ctx)world.querySelectorAll('.story h2').forEach(title=>{title.style.fontSize='';const css=getComputedStyle(title);ctx.font=css.font||`${css.fontWeight} ${css.fontSize} ${css.fontFamily}`;const widest=Math.max(...title.textContent.split(/\s+/).map(word=>ctx.measureText(word).width));if(widest>title.clientWidth)title.style.fontSize=(parseFloat(css.fontSize)*title.clientWidth/widest*.98)+'px';});
  const geo=geometry(),heights={};world.querySelectorAll('.story').forEach(el=>heights[el.dataset.event]=el.offsetHeight);layout=E.layout(visible,geo.width,geo.mobile,heights);positionElements();}
 function focusDay(clientY=innerHeight*.44){return layout.dayAt(clientY-world.getBoundingClientRect().top);}
 function goDay(day){const top=world.getBoundingClientRect().top+scrollY;window.scrollTo(0,Math.max(0,top+layout.position(day)-innerHeight*.30));updatePosition();}
 function refresh(){render();}
 function updatePosition(){const day=focusDay(),d=new Date(E.START+Math.round(day)*E.DAY),y=d.getUTCFullYear(),m=d.getUTCMonth();$('#position-year').textContent=y;$('#position-month').textContent=d.getUTCDate()+' '+months[m];$('#ambient-year').textContent=y;$('#elapsed').style.height=Math.max(0,layout.position(day)-55)+'px';}
 function jumpYear(y){const item=visible.find(e=>e.date.slice(0,4)===String(y));goDay(item?E.ordinal(item.date):E.ordinal(`${y}-01-01`));}
 function open(){if(!detail.open){lastFocus=document.activeElement;detail.showModal();document.body.classList.add('modal-open');}detail.scrollTop=0;}
 function sourcesHTML(e){return `<div class="sources-heading">CONSULTE AS FONTES</div>${e.sources.map(s=>`<a class="source-link" href="${url(s.url)}" target="_blank" rel="noopener noreferrer">${esc(s.name)} ↗<small>${s.published?'Publicação: '+format(s.published)+' · ':''}${esc(new URL(s.url).hostname)}</small></a>`).join('')}`;}
 function showEvent(id){const e=events.find(e=>e.id===id);if(!e)return;activeEvent=e;const n=events.indexOf(e);$('#dialog-label').textContent=`${short(e.date)} · ${themeFor(e).name.toUpperCase()}`;$('#dialog-label').style.color=themeFor(e).color;
  $('#dialog-content').innerHTML=`<div class="detail-date">${format(e.date)}</div><h2 id="detail-title">${headline(e)}</h2>${e.video?`<div id="video-slot">${videoHTML(e)}</div>`:''}<p>${esc(e.summary)}</p>${e.image&&!e.video?`<figure style="margin:20px 0">${image(e,'detail-image')}<figcaption class="caption">${esc(e.image.credit)}${e.image.context?' · '+esc(e.image.context):''}${e.image.license?' · '+esc(e.image.license):''}${e.image.sourceUrl?` · <a href="${url(e.image.sourceUrl)}" target="_blank" rel="noopener noreferrer">Origem ↗</a>`:''}</figcaption></figure>`:''}${sourcesHTML(e)}<div class="dialog-actions"><button id="previous" ${n===0?'disabled':''}>← Anterior</button><button id="copy">Copiar link</button><button id="next" ${n===events.length-1?'disabled':''}>Próximo →</button></div>`;
  try{history.replaceState(null,'',`${location.pathname}${location.search}#${e.id}`);}catch{}open();
  $('#previous').onclick=()=>showEvent(events[n-1].id);$('#next').onclick=()=>showEvent(events[n+1].id);
  $('#copy').onclick=async()=>{try{await navigator.clipboard.writeText(location.href);$('#copy').textContent='Link copiado';}catch{$('#copy').textContent='Copie o endereço da página';}};

 }
 function about(){clearTimeout(introTimer);activeEvent=null;$('#dialog-label').textContent='FONTES E CRITÉRIOS';$('#dialog-content').innerHTML=`<h2 id="detail-title">Sobre a linha do tempo.</h2><p>${events.length} registros de janeiro de 2019 até a invasão das sedes dos Três Poderes em 8 de janeiro de 2023. O mandato terminou em 31 de dezembro de 2022.</p><p><strong>Como percorrer.</strong> Role a página para avançar no tempo. O indicador no alto permite escolher um ano. As cores dos pontos indicam os temas; os resumos relatam as notícias e identificam a origem das alegações. Todas as manchetes aparecem na linha do tempo; toque em qualquer uma para abrir o registro e suas fontes. As manchetes ocupam os dois lados conforme o espaço disponível, para manter a leitura compacta. Os destaques têm manchetes bem maiores, para permitir uma leitura rápida dos episódios centrais; os registros complementares permanecem visíveis em letras menores. Fotos e prévias de vídeos aparecem na linha do tempo apenas nos destaques; a mídia de todos os registros continua disponível ao abrir a notícia.</p><p><strong>Datas reais.</strong> O eixo segue a ordem dos dias. O espaçamento aumenta quando necessário para manter todas as manchetes legíveis, sem sobreposição. Cada ponto informa a data do acontecimento. Indicadores entram no dia da divulgação, com o período medido indicado; revelações posteriores são posicionadas na data dos atos relatados. Meses e anos são marcados no eixo central; as datas completas aparecem em cada notícia.</p><p><strong>Recorte editorial.</strong> A seleção é crítica, com destaque para episódios de alcance humano e institucional. Não existe nesta pesquisa uma série comparável de engajamento negativo de todos os episódios. Métricas publicadas aparecem apenas nos registros correspondentes. Destaque editorial não é ranking medido.</p><p><strong>Evidência.</strong> Manchetes e resumos são próprios. Os resumos distinguem denúncias, investigações e decisões conforme o relato das fontes. Ações de familiares, ministros e apoiadores não são automaticamente atribuídas ao presidente. Resultados econômicos incluem contexto externo.</p><p><strong>Imagens e vídeos.</strong> ${events.filter(e=>e.image).length} notícias com fotografia e ${events.filter(e=>e.video).length} com registro audiovisual. Fotografias têm autoria e origem nos registros. Imagens de arquivo ou produzidas depois do acontecimento são identificadas na legenda. Vídeos só são carregados ao clicar. As fontes externas abrem em outra aba e podem ter restrições de acesso.</p><a class="source-link" href="pesquisa.md" download>Baixar a pesquisa completa ↗</a><a class="source-link" href="events.json" download>Baixar a base em JSON ↗</a><p class="caption">Pesquisa inicial: 5 de outubro de 2026. Sem anúncios ou análise de audiência.</p>`;open();}
 document.addEventListener('click',ev=>{const b=ev.target.closest('button');if(!b)return;if(b.dataset.event)showEvent(b.dataset.event);else if(b.dataset.year){if(picker.open)picker.close();jumpYear(b.dataset.year);}});
 $('#top-button').onclick=()=>window.scrollTo(0,0);$('#about').onclick=about;
 $('#years-button').onclick=()=>{clearTimeout(introTimer);picker.showModal();document.body.classList.add('modal-open');};$('#close-picker').onclick=()=>picker.close();picker.addEventListener('close',()=>{if(!detail.open)document.body.classList.remove('modal-open');});
 $('#close').onclick=()=>detail.close();detail.addEventListener('close',()=>{document.body.classList.remove('modal-open');const frame=$('#video-slot');if(frame)frame.innerHTML='';if(activeEvent&&location.hash===`#${activeEvent.id}`){try{history.replaceState(null,'',location.pathname+location.search);}catch{}}if(lastFocus?.isConnected)lastFocus.focus({preventScroll:true});});
 for(const d of [detail,picker])d.addEventListener('click',ev=>{if(ev.target===d){const r=d.getBoundingClientRect();if(ev.clientX<r.left||ev.clientX>r.right||ev.clientY<r.top||ev.clientY>r.bottom)d.close();}});
 addEventListener('scroll',()=>{if(scrollY>30)document.body.classList.add('scrolled');if(!scrollQueued){scrollQueued=true;requestAnimationFrame(()=>{updatePosition();scrollQueued=false;});}},{passive:true});

 let resizeTimer,layoutWidth=innerWidth;addEventListener('resize',()=>{if(innerWidth===layoutWidth){updatePosition();return;}layoutWidth=innerWidth;clearTimeout(resizeTimer);resizeTimer=setTimeout(()=>{const day=focusDay();refresh();goDay(day);},180);});
 refresh();
 if(document.fonts)document.fonts.ready.then(()=>fitStories());
 const linked=events.find(e=>e.id===location.hash.slice(1));if(linked){goDay(E.ordinal(linked.date));showEvent(linked.id);}
})();
